run execute for notebooks too

diff --git a/.github/workflows/pre-commit.yaml b/.github/workflows/pre-commit.yaml
--- a/.github/workflows/pre-commit.yaml
+++ b/.github/workflows/pre-commit.yaml
@@ -66,7 +66,7 @@ jobs:
         shell: micromamba-shell {0}
         run: |
           echo "Validating MyST Markdown files"
-          myst build --check *.md || echo "MyST Markdown validation failed"
+          myst build --execute --check-links  || echo "MyST Markdown validation failed"
         continue-on-error: true
 
       - name: Pre-commit feedback
